### ISSUE TITLE
Binnies Extrabees. [GreenMachine773][CF]

### ISSUE THREAD

**Issue by TheRealZeher** [TheRealZeher/DimensionalPocketsII#12]
java.lang.NullPointerException: Exception ticking world
    at net.minecraftforge.common.BiomeDictionary.getBiomeInfo(BiomeDictionary.java:363)
    at net.minecraftforge.common.BiomeDictionary.hasAnyType(BiomeDictionary.java:245)
    at net.minecraftforge.common.BiomeDictionary.ensureHasTypes(BiomeDictionary.java:371)
    at net.minecraftforge.common.BiomeDictionary.getTypes(BiomeDictionary.java:208)
    at net.minecraftforge.common.BiomeDictionary.hasType(BiomeDictionary.java:236)
    at binnie.extrabees.worldgen.WorldGenHiveNether.func_180709_b(WorldGenHiveNether.java:25)
    at binnie.extrabees.worldgen.ExtraBeesWorldGenerator.generateHive(ExtraBeesWorldGenerator.java:39)
    at binnie.extrabees.worldgen.ExtraBeesWorldGenerator.lambda$generate$0(ExtraBeesWorldGenerator.java:29)
    at java.lang.Iterable.forEach(Unknown Source)
    at binnie.extrabees.worldgen.ExtraBeesWorldGenerator.generate(ExtraBeesWorldGenerator.java:29)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at micdoodle8.mods.galacticraft.core.TransformerHooks.otherModGenerate(TransformerHooks.java:183)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1016)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:987)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:220)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
    at java.lang.Thread.run(Unknown Source)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Server thread
Stacktrace:
    at net.minecraftforge.common.BiomeDictionary.getBiomeInfo(BiomeDictionary.java:363)
    at net.minecraftforge.common.BiomeDictionary.hasAnyType(BiomeDictionary.java:245)
    at net.minecraftforge.common.BiomeDictionary.ensureHasTypes(BiomeDictionary.java:371)
    at net.minecraftforge.common.BiomeDictionary.getTypes(BiomeDictionary.java:208)
    at net.minecraftforge.common.BiomeDictionary.hasType(BiomeDictionary.java:236)
    at binnie.extrabees.worldgen.WorldGenHiveNether.func_180709_b(WorldGenHiveNether.java:25)
    at binnie.extrabees.worldgen.ExtraBeesWorldGenerator.generateHive(ExtraBeesWorldGenerator.java:39)
    at binnie.extrabees.worldgen.ExtraBeesWorldGenerator.lambda$generate$0(ExtraBeesWorldGenerator.java:29)
    at java.lang.Iterable.forEach(Unknown Source)
    at binnie.extrabees.worldgen.ExtraBeesWorldGenerator.generate(ExtraBeesWorldGenerator.java:29)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at micdoodle8.mods.galacticraft.core.TransformerHooks.otherModGenerate(TransformerHooks.java:183)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1016)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:987)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:220)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

**Comment by TheRealZeher** [comment]
Incorrect Biome Setup.
