### ISSUE TITLE
Sponge-Forge1.12.2!

### ISSUE THREAD

**Issue by xingcheng2** [TheRealZeher/DimensionalPocketsII#16]
Can not be used with spongeforge1.12.2!
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2705-7.1.0-BETA-3389.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 18-8-15 下午10:59
Description: Exception in server tick loop

java.lang.NullPointerException: type
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.getBiomeSettings(SpongeChunkGenerator.java:213)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:170)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:3594)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:822)
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:764)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3545)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.getBiomeSettings(SpongeChunkGenerator.java:213)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:170)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:3594)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:822)

-- Sponge PhaseTracker --
Details:
	Phase Stack: /**********************************************************************************************************************************/
/*   - Phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION}                                                        */
/*     Context:                                                                                                                   */
/*     - CapturedBlockPosition: CaptureBlockPos{pos=null, world=Optional.empty}                                                   */
/*     - World: WorldServer{Name=DIM98, DimensionId=98, DimensionType=dimensionalpocketsii:pocket_dimension, DimensionTypeId=98}  */
/*   - Phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION}                                                        */
/*     Context:                                                                                                                   */
/*     - Source: WorldServer{Name=DIM98, DimensionId=98, DimensionType=dimensionalpocketsii:pocket_dimension, DimensionTypeId=98} */
/*     - CapturedBlockPosition: CaptureBlockPos{pos=null, world=Optional.empty}                                                   */
/*     - World: WorldServer{Name=DIM98, DimensionId=98, DimensionType=dimensionalpocketsii:pocket_dimension, DimensionTypeId=98}  */
/**********************************************************************************************************************************/

Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjj000(MinecraftServer.java:3982)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 334002800 bytes (318 MB) / 1576534016 bytes (1503 MB) up to 1834483712 bytes (1749 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2749 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                   | Version                     | Source                                      | Signature                                |
	|:------- |:-------------------- |:--------------------------- |:------------------------------------------- |:---------------------------------------- |
	| UCHIJAA | minecraft            | 1.12.2                      | minecraft.jar                               | None                                     |
	| UCHIJAA | mcp                  | 9.42                        | minecraft.jar                               | None                                     |
	| UCHIJAA | FML                  | 8.0.99.99                   | forge-1.12.2-14.23.4.2749-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | forge                | 14.23.4.2749                | forge-1.12.2-14.23.4.2749-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | spongeapi            | 7.1.0-SNAPSHOT-7105dfc      | spongeforge-1.12.2-2705-7.1.0-BETA-3389.jar | None                                     |
	| UCHIJAA | sponge               | 1.12.2-2705-7.1.0-BETA-3389 | spongeforge-1.12.2-2705-7.1.0-BETA-3389.jar | 6729a677746f8cf63ef31881f913ed15d431b7f0 |
	| UCHIJAA | trzlib               | 2.1.8                       | TRZLib-1.12.2.jar                           | None                                     |
	| UCHIJAA | dimensionalpocketsii | 1.2.10-beta                 | Dimensional-Pockets-2-Mod-1.12.2.jar        | None                                     |

	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.12.2-2705-7.1.0-BETA-3389.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by TheRealZeher** [comment]
Thanks for posting the log. I'll take a look into it asap.

**Comment by xingcheng2** [comment]
[debug.log](https://github.com/TheRealZeher/DimensionalPockets-II/files/2301209/debug.log)
[latest.log](https://github.com/TheRealZeher/DimensionalPockets-II/files/2301210/latest.log)
[crash-2018-08-20_13.24.46-server.txt](https://github.com/TheRealZeher/DimensionalPockets-II/files/2301212/crash-2018-08-20_13.24.46-server.txt)

**Comment by xingcheng2** [comment]
When loading DIM98 world, BUG appears!

**Comment by TheRealZeher** [comment]
Cant seem to load in spongeforge into my development environment. I will keep trying, if not i will load all into an actual minecraft game and test from there.

**Comment by TheRealZeher** [comment]
Issue should be resolved. Incorect Biome setup.
