### ISSUE TITLE
Crash with Buildcraft and Galacticraft. [GoldenIvar22397][CF]

### ISSUE THREAD

**Issue by TheRealZeher** [TheRealZeher/DimensionalPocketsII#9]
java.lang.NullPointerException: Exception ticking world
    at buildcraft.energy.generation.OilGenerator.getStructures(OilGenerator.java:100)
    at buildcraft.energy.generation.OilGenerator.generate(OilGenerator.java:68)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at micdoodle8.mods.galacticraft.core.TransformerHooks.otherModGenerate(TransformerHooks.java:184)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1018)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
    at java.lang.Thread.run(Thread.java:745)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Server thread
Stacktrace:
    at buildcraft.energy.generation.OilGenerator.getStructures(OilGenerator.java:100)
    at buildcraft.energy.generation.OilGenerator.generate(OilGenerator.java:68)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at micdoodle8.mods.galacticraft.core.TransformerHooks.otherModGenerate(TransformerHooks.java:184)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1018)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

https://pastebin.com/2CcdxjBJ

**Comment by TheRealZeher** [comment]
Incorrect Biome Setup.
